
function GetInformation(title, lang = null)
{
	if (!lang)
		lang = Convars.GetStr("cl_language");
	
	local info = InformationText.english;
	switch (lang)
	{
		case "schinese":
		case "tchinese":
			info = InformationText.schinese;
			break;
		//case "english":
		//default:
			//info = InformationText.english;
	}
	
	return !(title in info) ? null : strip(info[title].reduce(@(a, b) a + "\n" + b));
}

InformationText <-
{
	english =
	{
		help_doc =
		[
			"This is an information file.",
			"",
			"About key binding",
			"    These three settings: \"ActivateButton, CombineButton, InspectButton\" can be changed to other button.",
			"    There are many buttons in the game: BUTTON_ATTACK, BUTTON_JUMP, BUTTON_DUCK, BUTTON_FORWARD, BUTTON_BACK, BUTTON_USE, BUTTON_CANCEL, BUTTON_LEFT, BUTTON_RIGHT, BUTTON_MOVELEFT, BUTTON_MOVERIGHT, BUTTON_SHOVE, BUTTON_RUN, BUTTON_RELOAD, BUTTON_ALT1, BUTTON_ALT2, BUTTON_SCORE, BUTTON_WALK, BUTTON_ZOOM, BUTTON_WEAPON1, BUTTON_WEAPON2, BUTTON_BULLRUSH, BUTTON_GRENADE1, BUTTON_GRENADE2, BUTTON_LOOKSPIN",
			"    But very few of them are suitable. So you can also use the bind command to binding any key, need to set these settings to 0 first.",
			"    Check some special keys' name in here: https://developer.valvesoftware.com/wiki/Bind#Special_Keys",
			"    Then add the following to Left 4 Dead 2/left4dead2/cfg/autoexec.cfg, after finished, enter exec autoexec in the console.",
			"        alias \"+ads_switch\" \"scripted_user_func ads_key_pressed,1\"",
			"        alias \"-ads_switch\" \"scripted_user_func ads_key_pressed,0\"",
			"        alias \"+ads_combine_switch\" \"scripted_user_func combine_key_pressed,1\"",
			"        alias \"-ads_combine_switch\" \"scripted_user_func combine_key_pressed,0\"",
			"        alias \"+ads_inspect_switch\" \"scripted_user_func inspect_key_pressed,1\"",
			"        alias \"-ads_inspect_switch\" \"scripted_user_func inspect_key_pressed,0\"",
			"",
			"///////////////////////////////////////////////////////////",
			"",
			"\"Settings\"",
			"    ActivateButton = BUTTON_ZOOM",
			"        The button used to activate the ADS, supports toggle mode and holding mode.",
			"        These are the supported buttons, only single button.",
			"            BUTTON_ATTACK = 1        // Fire (left mouse)",
			"            BUTTON_DUCK = 4          // Duck (ctrl)",
			"            BUTTON_WALK = 131072     // Walk (shift)",
			"            BUTTON_ZOOM = 524288     // Zoom (middle mouse), bad with Sniper, quit zoom also quit ADS",
			"",
			"        You can also use the bind command to bind any key, need to set ActivateButton to 0 first.",
			"        Here we take binding the mouse side buttons as an example, open the console and enter the following:",
			"            bind \"MOUSE4\" \"+ads_switch\"",
			"",
			"        You can also bind exists key, here we take binding Walk button (shift) as an example.",
			"        Add the following to Left 4 Dead 2/left4dead2/cfg/autoexec.cfg, after finished, enter exec autoexec in the console.",
			"            alias \"+key_walk\" \"+speed; +ads_switch\"",
			"            alias \"-key_walk\" \"-speed; -ads_switch\"",
			"            bind \"SHIFT\" \"+key_walk\"",
			"",
			"    SmartHoldingKey = 0.5",
			"        If holding the activate button over this time, will switch to holding mode.",
			"        0 = holding mode",
			"",
			"    CombineButton = BUTTON_USE",
			"        Model support required.",
			"        Click use button to toggle aim mode while ads. holding the button to flip the scope.",
			"        To use custom binding key:",
			"            bind \"MOUSE5\" \"+ads_combine_switch\"",
			"",
			"    CombineBtnHolding = 0.5",
			"        Holding for this time to flip the scope. Otherwise, it is considered a single click.",
			"",
			"    AttackRetreatDelay = 1.5",
			"        It will force set holding mode if use the BUTTON_ATTACK button, and quit ADS after not firing weapon for this many seconds.",
			"",
			"    FovScaling = 0",
			"        Scaling your FOV (fov_desired) when enter/exit ads, only works for the host.",
			"        0 = disable, 1 = enable",
			"",
			"    FovADS = 75",
			"        Zoom FOV to the set value when aiming, host only.",
			"        min. 75, max. 120",
			"",
			"    FovDefault = -1",
			"        Reset FOV to the set value when loading map, host only.",
			"        min. 75, max. 120",
			"        -1 = disable",
			"",
			"    RecoilFactor = 0.5",
			"        Recoil will multiply by this number.",
			"",
			"    SpreadReduce = 1",
			"        Cannot change spread & pellet scatter with vscript, but I can give you a temporary laser sight.",
			"",
			"    HideLaserSight = 1",
			"        Hide laser sight while ADS on.",
			"        0 = not hide, 1 = always hide, 2 = only hide temp laser sight",
			"        r_draw_lasersight_1st_person, this console command has hidden flag which mean it can only be modified for the host.",
			"",
			"    HideBulletTracers = 0",
			"        Hide bullet tracers.",
			"        0 = not hide, 1 = only hide while ads on, 2 = always hide",
			"        r_drawtracers_firstperson, this console command has hidden flag which mean it can only be modified for the host.",
			"",
			"    ForceEmptyReloadAnim = 1",
			"        Always play the \"empty reload\" anim (if exists) after emptying the magazine while ADS on if there is no \"ads empty reload\" anim.",
			"",
			"    ForceWalk = 0",
			"        Force player walk when ADS on.",
			"",
			"    OffADS_InReload = 1",
			"        Quit ADS when reloading.",
			"        0 = not quit, 1 = quit if no \"ads reload\" anim, 2 = always quit",
			"",
			"    OffADS_InShove = 2",
			"        Quit ADS when shoving.",
			"        0 = not quit, 1 = quit if no \"ads shove\" anim, 2 = always quit",
			"",
			"    OffADS_Restart = 0",
			"        Restart ADS after quit due to the above reasons, it will not restart if there are any new key actions.",
			"",
			"    OldDeployStyle = 0",
			"        Swap the deploy and draw animations, just like the original plugin v1.1.",
			"        0 = disable, 1 = enable",
			"",
			"    DisableInspect = 0",
			"        Enable or disable inspect.",
			"        0 = enable inspect, 1 = disable inspect, 2 = disable inspect when \"Inspect Weapon [VScript]\" installed",
			"",
			"    InspectButton = BUTTON_RELOAD",
			"        Inspect weapon via click the reload button while full magazine.",
			"        To use custom binding key:",
			"            bind \"i\" \"+ads_inspect_switch\"",
			"",
			"    HolsterWeapon = 0",
			"        Weapons will play the holster animation first (if exists), and then switch weapons, double click will switch weapons immediately.",
			"        It works well in local.",
			"",
			"    ManualReload = 2",
			"        Weapons do not automatically reload after run out of ammo.",
			"        0 = disable, use game logic, 1 =  manually press R button, 2 = manually reload when the model has IDLE_EMPTY animation",
			"",
			"    PreventShotgunReloadFiring = 0",
			"        Not allowed the shotgun fire while reloading, if you want to fire, it will interrupt the reloading.",
			"",
			"    IgnoreClient = 0",
			"        Prevent client use ads, this will avoid animations bug if client use different models with the host.",
			"",
			"    StableMode = 1",
			"        In stable mode, some problematic ads animations are disabled, and some features that have not been rigorously tested are also disabled.",
			"        0 = disable, 1 = enable",
			"",
			"Chat Commands(use \"!ads \" as prefix):",
			"    Command    Parameter                        Description",
			"",
			"    enable     [1|0]                            allow/disallow player to use ads.",
			"                                                example:",
			"                                                !ads enable 0",
			"                                                ",
			"    reload                                      when you change files after game started, use it.",
			"                                                admin only.",
			"",
			"    debug                                       print animations infomation in console for held weapon.",
			"                                                admin only.",
			"",
			"    play       <sequence id|animation name>     play the animation if exists.",
			"                                                example:",
			"                                                !ads play ACT_PRIMARY_VM_IDLE",
		],
		activity_list =
		[
			"// v1.1: https://github.com/IA-NanaNana/l4d2-aim-down-sight",
			"Original plugin author: @NanaNana(鳴海兎亜)",
			"Instructions to mod authors on creating ADS:",
			"  Using delta in firing animation (ACT_VM_PRIMARYATTACK_LAYER).",
			"",
			"",
			"Version " + Version,
			"Includes all new animations. Completed by @Observeye(瞑睦) and me.",
			"Marked with \"*\" are official animations.",
			"",
			"///////////////////////",
			"///////// HIP /////////",
			"///////////////////////",
			"// Scope transform [Note 4]",
			"ACT_VM_MIXED_ON     // Switch to second state",
			"ACT_VM_MIXED_OFF    // Restore to default state",
			"",
			"// For all weapons",
			"ACT_VM_IDLE                   // *Default idle, the hunting rifle: ACT_VM_IDLE_SNIPER",
			"ACT_VM_IDLE_EMPTY             // Empty idle",
			"ACT_VM_IDLE_TRANS             // Interim idle [Note 1]",
			"ACT_VM_DEPLOY_LAYER           // *First pickup, the hunting rifle: ACT_VM_DEPLOY_SNIPER_LAYER",
			"ACT_VM_DRAW_LAYER             // Draw weapon",
			"ACT_VM_HOLSTER_LAYER          // Holster weapon, don't use ACT_VM_HOLSTER, it's bugged",
			"ACT_VM_PRIMARYATTACK_LAYER    // *Firing, the hunting rifle: ACT_VM_SHOOT_SNIPER_LAYER",
			"ACT_VM_DRYFIRE                // The last bullet, for dual pistols is the second to last bullet",
			"ACT_VM_RELOAD_LAYER           // *Reloading, the hunting rifle: ACT_VM_RELOAD_SNIPER_LAYER",
			"ACT_VM_RELOAD_EMPTY_LAYER     // Empty reloading [Note 2]",
			"ACT_VM_MELEE_LAYER            // *Shove, the hunting rifle: ACT_VM_MELEE_SNIPER_LAYER",
			"ACT_VM_MELEE_HIT              // Shove and hit something",
			"ACT_VM_MELEE_KILL             // Shove and kill something",
			"ACT_VM_FIDGET                 // Inspect",
			"ACT_VM_FIDGET_EMPTY           // Empty inspect",
			"",
			"// *Dual pistols",
			"ACT_VM_IDLE_LOWERED             // The first pistol keep this until fring the last ammo or reload",
			"ACT_VM_SECONDARYATTACK_LAYER    // Firing of the Secondary pistol",
			"ACT_VM_DRYFIRE_LEFT             // The last bullet of the secondary pistol",
			"",
			"// Shotgun",
			"// *Reloading",
			"ACT_VM_RELOAD_LAYER",
			"ACT_VM_RELOAD_LOOP_LAYER",
			"ACT_VM_RELOAD_END_LAYER",
			"// Empty reloading",
			"ACT_VM_RELOAD_EMPTY_LAYER    // [Note 3]",
			"ACT_VM_RELOAD_EMPTY_LOOP",
			"ACT_VM_RELOAD_EMPTY_END",
			"// Magazine reloading, if exists, this mode will be forced to be used",
			"ACT_VM_RELOAD_MAGAZINE_LAYER          // [Note 2]",
			"ACT_VM_RELOAD_MAGAZINE_EMPTY_LAYER    // [Note 2]",
			"",
			"// Lever action rifles",
			"// Reloading",
			"ACT_VM_RELOAD_START_LAYER    // [Note 3]",
			"ACT_VM_RELOAD_LOOP",
			"ACT_VM_RELOAD_END",
			"// Empty reloading",
			"ACT_VM_RELOAD_EMPTY_START_LAYER    // [Note 3]",
			"ACT_VM_RELOAD_EMPTY_LOOP",
			"ACT_VM_RELOAD_EMPTY_END",
			"",
			"",
			"///////////////////////",
			"///////// ADS /////////",
			"///////////////////////",
			"This list only shows the main ads, the others are simply different prefixes.",
			"ACT_SECONDARY_VM_IDLE    // Second ads",
			"ACT_TERTIARY_VM_IDLE     // Third ads",
			"If using delta animation, simply adding the corresponding idle animation is also acceptable.",
			"",
			"// Scope transform [Note 4]",
			"ACT_PRIMARY_VM_MIXED_ON     // Switch to second state",
			"ACT_PRIMARY_VM_MIXED_OFF    // Restore to default state",
			"",
			"// For all weapons",
			"ACT_PRIMARY_VM_IDLE_TO_LOWERED       // From hip to ads",
			"ACT_PRIMARY_VM_LOWERED_TO_IDLE       // Exit ads to hip",
			"ACT_PRIMARY_VM_IDLE_TO_NEXT          // Toggle next ads mode",
			"ACT_PRIMARY_VM_IDLE                  // Default idle",
			"ACT_PRIMARY_VM_IDLE_EMPTY            // Empty idle",
			"ACT_PRIMARY_VM_IDLE_TRANS            // Interim idle [Note 1]",
			"ACT_PRIMARY_VM_PRIMARYATTACK         // Firing",
			"ACT_PRIMARY_VM_DRYFIRE               // The last bullet, for dual pistols is the second to last bullet",
			"ACT_PRIMARY_VM_RELOAD_LAYER          // Reloading [Note 2]",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_LAYER    // Empty reloading [Note 2]",
			"ACT_PRIMARY_VM_MELEE                 // Shove",
			"ACT_PRIMARY_VM_MELEE_HIT             // Shove and hit something",
			"ACT_PRIMARY_VM_MELEE_KILL            // Shove and kill something",
			"",
			"// Dual pistols",
			"ACT_PRIMARY_VM_IDLE_LOWERED       // The first pistol keep this until fring the last ammo or reload",
			"ACT_PRIMARY_VM_SECONDARYATTACK    // Firing of the Secondary pistol",
			"ACT_PRIMARY_VM_DRYFIRE_LEFT       // The last bullet of the secondary pistol",
			"",
			"// Shotgun",
			"// Reloading",
			"ACT_PRIMARY_VM_RELOAD_LAYER    // [Note 3]",
			"ACT_PRIMARY_VM_RELOAD_LOOP",
			"ACT_PRIMARY_VM_RELOAD_END",
			"// Empty reloading",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_LAYER    // [Note 3]",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_LOOP",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_END",
			"// Magazine reloading, if exists, this mode will be forced to be used",
			"ACT_PRIMARY_VM_RELOAD_MAGAZINE_LAYER          // [Note 2]",
			"ACT_PRIMARY_VM_RELOAD_MAGAZINE_EMPTY_LAYER    // [Note 2]",
			"",
			"// Lever action rifles",
			"// Reloading",
			"ACT_PRIMARY_VM_RELOAD_START_LAYER    // [Note 3]",
			"ACT_PRIMARY_VM_RELOAD_LOOP",
			"ACT_PRIMARY_VM_RELOAD_END",
			"// Empty reloading",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_START_LAYER    // [Note 3]",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_LOOP",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_END",
			"",
			"",
			"////////////////////////",
			"///////// NOTE /////////",
			"////////////////////////",
			"[1] Transition from empty idle to default idle.",
			"Copy \"default idle\" and set fadein to 0, this will fixed the empty reloading animations.",
			"Used to fix delta animations.",
			"Also not needed if no empty idle.",
			"",
			"[2] Add the \"_LAYER\" suffix to the reload animations.",
			"I only recently figured out that the vanilla game plays the ACT_VM_RELOAD_LAYER animation when reloading.",
			"However, it uses the duration of ACT_VM_RELOAD to set the next firing time. Huh?",
			"Please write qc according to this rule.",
			"#This is mainly to resolve issues with incorrect reload timing. If the animation duration is the same, the \"_LAYER\" suffix can be ignored.",
			"",
			"[3] Fixed the reload start animation for shotgun and Lever action rifles.",
			"Because it's not possible to leave the animation on the last frame like in the official one.",
			"Therefore, the only option is to increase the duration and obtain the accurate duration through animations without \"_LAYER\".",
			"Modify the start animations in the qc file like this:",
			"$sequence \"reload_empty\" {",
			"    ...",
			"    activity \"ACT_VM_RELOAD_EMPTY\" 1",
			"    ...",
			"}",
			"$sequence \"reload_empty_layer\" {",
			"    ...",
			"    activity \"ACT_VM_RELOAD_EMPTY_LAYER\" 1",
			"    numframes x // \"x\" according to animation' frames and fps, generally, you can just add the two numbers together",
			"    ...",
			"}",
			"",
			"[4] There are two methods to switch the scope state.",
			"The simplest method is to use non-delta animation, simply add the \"MIXED_\" prefix to all animations of the new state.",
			"Hip animations of new state:",
			"MIXED_ACT_VM_IDLE             // Default idle",
			"MIXED_ACT_VM_PRIMARYATTACK    // Firing",
			"No need to add the \"MIXED_\" prefix to the transform animations.",
			"",
			"// https://developer.valvesoftware.com/wiki/$bodygroup",
			"The second method uses $bodygroup.",
			"Two modes are supported in total, choose the one that best suits your desired effect.",
			"Note that the newly added $bodygroup needs to be placed in the third position or later, because the first two body group cannot be changed.",
			"",
			"Holographic Hybrid Sight",
			"This mode emphasizes change the appearance, the scopes vision only having two states: off and on.",
			"$bodygroup \"scope_transform\"",
			"{",
			"    studio \"mixed_off_scope_off_50.smd\"    // Default state, PiP off",
			"    studio \"mixed_off_scope_on.smd\"        // Default state, PiP on, when looking at the scope in main ads",
			"    studio \"mixed_on_scope_off_30.smd\"     // Second state, PiP off",
			"    studio \"mixed_on_scope_on.smd\"         // Second state, PiP on, made the PiP to be closed at the correct time.",
			"}",
			"",
			"Low Power Variable Optic",
			"This mode offers two zoom levels and also can change the appearance.",
			"Whether the scopes vision is displayed should be controlled by the idle.",
			"$bodygroup \"scope_variable\"",
			"{",
			"    studio \"mixed_off_x1_50.smd\"    // Low power",
			"    studio \"mixed_on_x4_50.smd\"     // High power",
			"",
			"    // Optional, enabled if the appearance changes",
			"    //studio \"mixed_off_x4.smd\"",
			"    //studio \"mixed_on_x1.smd\"",
			"}",
			"",
			"The last number in the studio name represents a percentage relative to the animation duration.",
			"That is, the final state only switches after playing the MIXED_OFF/MIXED_ON animationa for that many seconds.",
			"To achieve the effect of switching the scopes vision at the appropriate time.",
			"Because AE_CL_BODYGROUP_SET_VALUE is not working, Thanks Valve!",
			"",
			"If MIXED_OFF/MIXED_ON uses delta animation",
			"Then needs to set fadein to 0 and adjusted the animations to compensate for the misalignment when switching $bodygroup.",
		]
	}
	
	schinese =
	{
		help_doc =
		[
			"这是说明文档",
			"",
			"关于按键绑定",
			"    ActivateButton，CombineButton，InspectButton 这三个设置可以修改按键",
			"    游戏中的按键有很多：BUTTON_ATTACK, BUTTON_JUMP, BUTTON_DUCK, BUTTON_FORWARD, BUTTON_BACK, BUTTON_USE, BUTTON_CANCEL, BUTTON_LEFT, BUTTON_RIGHT, BUTTON_MOVELEFT, BUTTON_MOVERIGHT, BUTTON_SHOVE, BUTTON_RUN, BUTTON_RELOAD, BUTTON_ALT1, BUTTON_ALT2, BUTTON_SCORE, BUTTON_WALK, BUTTON_ZOOM, BUTTON_WEAPON1, BUTTON_WEAPON2, BUTTON_BULLRUSH, BUTTON_GRENADE1, BUTTON_GRENADE2, BUTTON_LOOKSPIN",
			"    但实际能用的不多，所以也可以使用 bind 命令来绑定任意按键, 需要先将对应设置的值修改为 0",
			"    可以在这里查看特殊按键的名称：https://developer.valvesoftware.com/wiki/Bind#Special_Keys",
			"    然后添加以下内容到 Left 4 Dead 2/left4dead2/cfg/autoexec.cfg，改好后在控制台执行一次 exec autoexec",
			"        alias \"+ads_switch\" \"scripted_user_func ads_key_pressed,1\"",
			"        alias \"-ads_switch\" \"scripted_user_func ads_key_pressed,0\"",
			"        alias \"+ads_combine_switch\" \"scripted_user_func combine_key_pressed,1\"",
			"        alias \"-ads_combine_switch\" \"scripted_user_func combine_key_pressed,0\"",
			"        alias \"+ads_inspect_switch\" \"scripted_user_func inspect_key_pressed,1\"",
			"        alias \"-ads_inspect_switch\" \"scripted_user_func inspect_key_pressed,0\"",
			"",
			"///////////////////////////////////////////////////////////",
			"",
			"\"Settings\"",
			"    ActivateButton = BUTTON_ZOOM",
			"        用于激活机瞄的按钮，支持切换和按住两种模式",
			"        这些是支持的按键，仅支持单一按键",
			"            BUTTON_ATTACK = 1        // 攻击，鼠标左键",
			"            BUTTON_DUCK = 4          // 蹲下，左Ctrl键",
			"            BUTTON_WALK = 131072     // 静步，左Shift键",
			"            BUTTON_ZOOM = 524288     // 开镜，鼠标中键，狙击枪不建议，取消瞄准镜状态也会退出机瞄",
			"",
			"        除了上面这些，还可以使用 bind 命令来绑定任意按键，需要先将 ActivateButton 设置为 0",
			"        这里以绑定鼠标侧键作为例子，待进入游戏后打开控制台，输入以下内容",
			"            bind \"MOUSE4\" \"+ads_switch\"",
			"",
			"        也可以绑定正在使用的按键，这里以静步(左Shift键)为例",
			"        添加以下内容到 Left 4 Dead 2/left4dead2/cfg/autoexec.cfg，改好后在控制台执行一次 exec autoexec",
			"            alias \"+key_walk\" \"+speed; +ads_switch\"",
			"            alias \"-key_walk\" \"-speed; -ads_switch\"",
			"            bind \"SHIFT\" \"+key_walk\"",
			"",
			"    SmartHoldingKey = 0.5",
			"        如果持续按住按钮的时间大于该值，则自动变成按住模式",
			"        0 = 始终为按住模式",
			"",
			"    CombineButton = BUTTON_USE",
			"        需要模型支持",
			"        机瞄状态下单击使用键可以切换不同的瞄准模式；长按可以翻转瞄准镜",
			"        还可以绑定自定义按键：",
			"            bind \"MOUSE5\" \"+ads_combine_switch\"",
			"",
			"    CombineBtnHolding = 0.5",
			"        按住设定的时长翻转瞄准镜，否则被认为是一次单击",
			"",
			"    AttackRetreatDelay = 1.5",
			"        如果绑定攻击键，那么会强制使用按住模式，并且在停止攻击这么多秒后才会退出机瞄",
			"",
			"    FovScaling = 0",
			"        进入/退出机瞄时缩放FOV（fov_desired），只有主机可用",
			"        0 = 关闭，1 = 启用",
			"",
			"    FovADS = 75",
			"        开启机瞄后缩放FOV到设定的值，只有主机可用",
			"        最小值为75，最大值为120",
			"",
			"    FovDefault = -1",
			"        加载地图时重置FOV为设定的值，只有主机可用",
			"        最小值为75，最大值为120",
			"        -1 = 关闭",
			"",
			"    RecoilFactor = 0.5",
			"        后坐力会乘以这个数值",
			"",
			"    SpreadReduce = 1",
			"        不能通过VScript修改子弹散射，但可以给一个临时的激光瞄准器",
			"",
			"    HideLaserSight = 1",
			"        机瞄开启时隐藏激光瞄准器",
			"        0 = 不隐藏，1 = 始终隐藏，2 = 仅隐藏临时激光",
			"        r_draw_lasersight_1st_person，这个控制台命令具有隐藏属性，所以只能在主机上修改",
			"",
			"    HideBulletTracers = 0",
			"        隐藏弹道轨迹",
			"        0 = 不隐藏，1 = 仅机瞄开启时隐藏，2 = 始终隐藏",
			"        r_drawtracers_firstperson，这个控制台命令具有隐藏属性，所以只能在主机上修改",
			"",
			"    ForceEmptyReloadAnim = 1",
			"        机瞄状态下，如果武器没有机瞄空膛换弹但有普通空膛换弹动画，则播放普通空膛换弹动画",
			"",
			"    ForceWalk = 0",
			"        机瞄开启时强制玩家静步",
			"",
			"    OffADS_InReload = 1",
			"        换子弹的时候退出机瞄",
			"        0 = 不退出，1 = 没有机瞄换弹的动画才退出，2 = 始终退出",
			"",
			"    OffADS_InShove = 2",
			"        推的时候退出机瞄",
			"        0 = 不退出，1 = 没有机瞄推的动画才退出，2 = 始终退出",
			"",
			"    OffADS_Restart = 0",
			"        因上诉原因退出机瞄后自动重新激活，如果有任何新的按键动作，则不会再次激活",
			"",
			"    OldDeployStyle = 0",
			"        交换初次捡起和拔枪的动画，就像插件v1.1那样",
			"        0 = 关闭，1 = 启用",
			"",
			"    DisableInspect = 0",
			"        启用或者禁用检视",
			"        0 = 启用检视，1 = 禁用检视，2 = 安装了\"检视武器 [VScript]\"模组时禁用检视",
			"",
			"    InspectButton = BUTTON_RELOAD",
			"        满弹夹时按换弹键检视武器",
			"        还可以绑定自定义按键：",
			"            bind \"i\" \"+ads_inspect_switch\"",
			"",
			"    HolsterWeapon = 0",
			"        有收枪动画的武器会先播放收枪动画，然后才切换武器，双击可以立即切换",
			"        单人游戏的时候效果很好",
			"",
			"    ManualReload = 2",
			"        弹药打完后不会自动开始换弹，需手动按换弹键",
			"        0 = 禁用设置，使用游戏逻辑，1 = 手动按R进行换弹，2 = 模型有 IDLE_EMPTY 动画时手动进行换弹",
			"",
			"    PreventShotgunReloadFiring = 0",
			"        禁止霰弹枪在上子弹的时候开火，如果你想开火，则会中断换弹过程",
			"",
			"    IgnoreClient = 0",
			"        阻止客户端使用机瞄功能，这可以避免客户端因为使用和主机不同的武器模型而出现动画错误",
			"",
			"    StableMode = 1",
			"        稳定模式下屏蔽了一些可能存在问题的机瞄动画，同时也会禁用部分尚未严格测试的功能",
			"        0 = 关闭，1 = 启用",
			"",
			"聊天命令(先输入“!ads ”)：",
			"    命令       参数                        说明",
			"",
			"    enable     [0|1]                       禁止/允许 玩家使用机瞄功能",
			"                                           用例：",
			"                                           !ads enable 0",
			"",
			"    reload                                 当你在游戏中切出去修改了文件，可以用来重新加载设置",
			"                                           仅房主可用",
			"",
			"    debug                                  在控制台打印当前武器的所有动画信息以及正在播放的动画",
			"                                           仅房主可用",
			"",
			"    play       <动画编号|动画名称>         播放指定的动画，可以是数字编号，也可以是动画的名称",
			"                                           用例：",
			"                                           !ads play ACT_PRIMARY_VM_IDLE",
		],
		activity_list =
		[
			"// v1.1：https://github.com/IA-NanaNana/l4d2-aim-down-sight",
			"原插件作者：@NanaNana（鳴海兎亜）",
			"致MOD作者关于机瞄的制作说明：",
			"  需要在正常开火动画中（ACT_VM_PRIMARYATTACK_LAYER）使用delta",
			"",
			"",
			"当前版本 " + Version,
			"包含所有新增的动画，由 @Observeye（瞑睦）和我共同完成",
			"带“*”的为官方动画",
			"",
			"////////////////////////",
			"///////// 腰射 /////////",
			"////////////////////////",
			"// 瞄准镜变形 [注4]",
			"ACT_VM_MIXED_ON     // 切换到第二形态",
			"ACT_VM_MIXED_OFF    // 恢复到默认状态",
			"",
			"// 所有武器通用",
			"ACT_VM_IDLE                   // *默认待机，猎枪为 ACT_VM_IDLE_SNIPER",
			"ACT_VM_IDLE_EMPTY             // 空仓待机",
			"ACT_VM_IDLE_TRANS             // 过渡待机 [注1]",
			"ACT_VM_DEPLOY_LAYER           // *初次捡起武器，猎枪为 ACT_VM_DEPLOY_SNIPER_LAYER",
			"ACT_VM_DRAW_LAYER             // 拿出武器的动画，在切换武器后播放",
			"ACT_VM_HOLSTER_LAYER          // 收起武器的动画，在切换武器前播放，ACT_VM_HOLSTER 存在问题无法使用",
			"ACT_VM_PRIMARYATTACK_LAYER    // *开火，猎枪为 ACT_VM_SHOOT_SNIPER_LAYER",
			"ACT_VM_DRYFIRE                // 最后一发子弹，双手枪则是倒数第二发",
			"ACT_VM_RELOAD_LAYER           // *换弹，猎枪为 ACT_VM_RELOAD_SNIPER_LAYER",
			"ACT_VM_RELOAD_EMPTY_LAYER     // 空仓换弹 [注2]",
			"ACT_VM_MELEE_LAYER            // *推，猎枪为 ACT_VM_MELEE_SNIPER_LAYER",
			"ACT_VM_MELEE_HIT              // 推击中物体",
			"ACT_VM_MELEE_KILL             // 推击中并杀死物体",
			"ACT_VM_FIDGET                 // 检视",
			"ACT_VM_FIDGET_EMPTY           // 空仓检视",
			"",
			"// *双手枪",
			"ACT_VM_IDLE_LOWERED             // 主手枪空仓待机，只是循环动画，不是真正的待机动画",
			"ACT_VM_SECONDARYATTACK_LAYER    // 副手枪开火",
			"ACT_VM_DRYFIRE_LEFT             // 副手枪最后一发子弹",
			"",
			"// 霰弹枪",
			"// *换弹",
			"ACT_VM_RELOAD_LAYER",
			"ACT_VM_RELOAD_LOOP_LAYER",
			"ACT_VM_RELOAD_END_LAYER",
			"// 空仓换弹",
			"ACT_VM_RELOAD_EMPTY_LAYER    // [注3]",
			"ACT_VM_RELOAD_EMPTY_LOOP",
			"ACT_VM_RELOAD_EMPTY_END",
			"// 弹匣式换弹，只会使用此种换弹模式",
			"ACT_VM_RELOAD_MAGAZINE_LAYER          // [注2]",
			"ACT_VM_RELOAD_MAGAZINE_EMPTY_LAYER    // [注2]",
			"",
			"// 杠杆式步枪",
			"// 换弹",
			"ACT_VM_RELOAD_START_LAYER    // [注3]",
			"ACT_VM_RELOAD_LOOP",
			"ACT_VM_RELOAD_END",
			"// 空仓换弹",
			"ACT_VM_RELOAD_EMPTY_START_LAYER    // [注3]",
			"ACT_VM_RELOAD_EMPTY_LOOP",
			"ACT_VM_RELOAD_EMPTY_END",
			"",
			"",
			"////////////////////////",
			"///////// 机瞄 /////////",
			"////////////////////////",
			"这里只列出默认机瞄模式的动画，剩下两种只是前缀不同",
			"ACT_SECONDARY_VM_IDLE    // 第二机瞄",
			"ACT_TERTIARY_VM_IDLE     // 第三机瞄",
			"如果使用delta动画，只添加相应的待机动画也不是不行",
			"",
			"// 瞄准镜变形 [注4]",
			"ACT_PRIMARY_VM_MIXED_ON     // 切换到第二形态",
			"ACT_PRIMARY_VM_MIXED_OFF    // 恢复到默认状态",
			"",
			"// 所有武器通用",
			"ACT_PRIMARY_VM_IDLE_TO_LOWERED       // 从腰射进入机瞄",
			"ACT_PRIMARY_VM_LOWERED_TO_IDLE       // 退出机瞄到腰射",
			"ACT_PRIMARY_VM_IDLE_TO_NEXT          // 切换到下一个机瞄模式",
			"ACT_PRIMARY_VM_IDLE                  // 默认待机",
			"ACT_PRIMARY_VM_IDLE_EMPTY            // 空仓待机",
			"ACT_PRIMARY_VM_IDLE_TRANS            // 过渡待机 [注1]",
			"ACT_PRIMARY_VM_PRIMARYATTACK         // 开火",
			"ACT_PRIMARY_VM_DRYFIRE               // 最后一发子弹，双手枪则是倒数第二发",
			"ACT_PRIMARY_VM_RELOAD_LAYER          // 换弹 [注2]",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_LAYER    // 空仓换弹 [注2]",
			"ACT_PRIMARY_VM_MELEE                 // 推",
			"ACT_PRIMARY_VM_MELEE_HIT             // 推击中物体",
			"ACT_PRIMARY_VM_MELEE_KILL            // 推击中并杀死物体",
			"",
			"// 双手枪",
			"ACT_PRIMARY_VM_IDLE_LOWERED       // 主手枪空仓待机，只是循环动画，不是真正的待机动画",
			"ACT_PRIMARY_VM_SECONDARYATTACK    // 副手枪开火",
			"ACT_PRIMARY_VM_DRYFIRE_LEFT       // 副手枪最后一发子弹",
			"",
			"// 霰弹枪",
			"// 换弹",
			"ACT_PRIMARY_VM_RELOAD_LAYER    // [注3]",
			"ACT_PRIMARY_VM_RELOAD_LOOP",
			"ACT_PRIMARY_VM_RELOAD_END",
			"// 空仓换弹",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_LAYER    // [注3]",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_LOOP",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_END",
			"// 弹匣式换弹，只会使用此种换弹模式",
			"ACT_PRIMARY_VM_RELOAD_MAGAZINE_LAYER          // [注2]",
			"ACT_PRIMARY_VM_RELOAD_MAGAZINE_EMPTY_LAYER    // [注2]",
			"",
			"// 杠杆式步枪",
			"// 换弹",
			"ACT_PRIMARY_VM_RELOAD_START_LAYER    // [注3]",
			"ACT_PRIMARY_VM_RELOAD_LOOP",
			"ACT_PRIMARY_VM_RELOAD_END",
			"// 空仓换弹",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_START_LAYER    // [注3]",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_LOOP",
			"ACT_PRIMARY_VM_RELOAD_EMPTY_END",
			"",
			"",
			"////////////////////////",
			"///////// 注释 /////////",
			"////////////////////////",
			"[1] 从空仓待机过渡到默认待机",
			"复制“默认待机”并设置 fadein 0 以修复空仓换弹动画",
			"用于修复delta动画，非delta动画可以忽略",
			"没有空仓待机也可以忽略",
			"",
			"[2] 给换弹动画添加“_LAYER”后缀",
			"最近才弄明白，换弹的时候游戏默认播放 ACT_VM_RELOAD_LAYER 动画",
			"但是却使用 ACT_VM_RELOAD 的时长来设置下次开火的时间，嗯？",
			"还请按照这个规则来写qc",
			"#主要是为了解决换弹时间对不上的情况，如果动画时长一致，也可以不要“_LAYER”后缀",
			"",
			"[3] 修复霰弹枪以及杠杆式步枪的新增换弹的开始动画",
			"因为不能像官方动画那样让动画结束后仍然停留在最后一帧",
			"所以只能手动增加动画时间，并通过不带“_LAYER”的动画获取准确的动画时间",
			"按照下面的格式来修改qc：",
			"$sequence \"reload_empty\" {",
			"    ...",
			"    activity \"ACT_VM_RELOAD_EMPTY\" 1",
			"    ...",
			"}",
			"$sequence \"reload_empty_layer\" {",
			"    ...",
			"    activity \"ACT_VM_RELOAD_EMPTY_LAYER\" 1",
			"    numframes x // \"x\" 的值由该动画的帧数和fps共同决定，一般来说将两者相加就可以了",
			"    ...",
			"}",
			"",
			"[4] 目前有两种方法实现瞄准镜的切换",
			"最简单的方法是使用非delta动画，只需要给新形态的动画都加上“MIXED_”前缀即可",
			"新形态的腰射动画：",
			"MIXED_ACT_VM_IDLE             // 默认待机",
			"MIXED_ACT_VM_PRIMARYATTACK    // 开火",
			"切换动画无需增加“MIXED_”前缀",
			"",
			"// https://developer.valvesoftware.com/wiki/$bodygroup",
			"第二种方法使用 $bodygroup，无需额外添加“MIXED_”动画",
			"总共支持两种模式，根据想要的效果选择合适的即可",
			"注意新增的 $bodygroup 需要放在第三位或之后，因为无法修改前两个 $bodygroup",
			"",
			"变形，适用 HHS",
			"这种模式注重于形态的变化，镜内画面只有开启和关闭两种状态",
			"$bodygroup \"scope_transform\"",
			"{",
			"    studio \"mixed_off_scope_off_50.smd\"    // 默认形态，镜内关闭",
			"    studio \"mixed_off_scope_on.smd\"        // 默认形态，镜内开启，机瞄时看着主镜",
			"    studio \"mixed_on_scope_off_30.smd\"     // 第二形态，镜内关闭",
			"    studio \"mixed_on_scope_on.smd\"         // 第二形态，镜内开启，过渡用，以实现在正确的时间点关闭镜内",
			"}",
			"",
			"变倍，适用 LPVO",
			"这种模式拥有两种放大倍率，也可以有外观上的变化",
			"此时镜内画面的显示与否由待机动画控制",
			"$bodygroup \"scope_variable\"",
			"{",
			"    studio \"mixed_off_x1_50.smd\"    // 低倍率",
			"    studio \"mixed_on_x4_50.smd\"     // 高倍率",
			"",
			"    // 可选，如果有外观变化则启用",
			"    //studio \"mixed_off_x4.smd\"",
			"    //studio \"mixed_on_x1.smd\"",
			"}",
			"",
			"studio 名称中最后的数字表示相对于动画时长的百分比",
			"即播放 MIXED_OFF/MIXED_ON 动画这么多秒后，才切换到最终形态",
			"以实现在恰当的时间点切换镜内画面的效果",
			"这就不得不感谢v社了，AE_CL_BODYGROUP_SET_VALUE 不起作用",
			"",
			"如果 MIXED_OFF/MIXED_ON 使用的是delta动画",
			"则需要设置 fadein 0 并调整动画以匹配因切换 $bodygroup 造成的错位问题",
		]
	}
}

